# Generate release for linux

name: GenerateLinuxRelease

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: |
          python3 -m pip install --upgrade pip
          pip install -r src/requirements.txt
          pip install pyinstaller
      #    python3 -m pip install pygame==1.9.6
      #    python3 -c "import pygame;print('hello')"

      #- name: PyInstaller Linux ReWordle Console
      #  # You may pin to the exact commit or the version.
      #  # uses: JackMcKew/pyinstaller-action-linux@38639c352a36917eea765f9283bfd1092c28af7b
      #  uses: JackMcKew/pyinstaller-action-linux@main
      #  with:
      #    # Directory containing source code & .spec file (optional requirements.txt).
      #    path: src # default is src
      #    # Specify a file path for .spec file
      #    spec: re_wordle_console.spec # optional, default is
      #- name: PyInstaller Linux ReWordle Windowed
      #  # You may pin to the exact commit or the version.
      #  # uses: JackMcKew/pyinstaller-action-linux@38639c352a36917eea765f9283bfd1092c28af7b
      #  uses: JackMcKew/pyinstaller-action-linux@main
      #  with:
      #    # Directory containing source code & .spec file (optional requirements.txt).
      #    path: src # default is src
      #    # Specify a file path for .spec file
      #    spec: re_wordle_windowed.spec # optional, default is
      - name: PyInstaller Linux ReWordle Console
        run:
          python3 -m PyInstaller src/re_wordle_console.spec
      - name: PyInstaller Linux ReWordle Windowed
        run:
          python3 -m PyInstaller src/re_wordle_windowed.spec
      - uses: actions/upload-artifact@v2
        with:
          name: packaged-binaries
          path: src/dist/linux
      
      - name: Echo directory
        run: ls dist/
      #zip up files
      - uses: papeloto/action-zip@v1
        with:
          files: dist/rewordle_console dist/rewordle_windowed LICENSE.txt README.md
          dest: linux_binaries.zip
      #auto release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest-linux"
          prerelease: false
          title: "Development Build - Linux"
          files: |
            LICENSE.txt
            linux_binaries.zip
